import React from 'react';
import { DollarSign, Hotel, Utensils, Car, Compass, HelpCircle } from 'lucide-react';
import { formatCurrency } from '../utils/helpers';

export default function BudgetBreakdown({ budgetData }) {
  const { accommodation = 0, food = 0, transport = 0, activities = 0, misc = 0, total = 0, currency = 'INR' } = budgetData || {};

  const categories = [
    { name: 'Accommodation', amount: accommodation, color: 'bg-purple-500', text: 'text-purple-400', icon: Hotel },
    { name: 'Food & Dining', amount: food, color: 'bg-amber-500', text: 'text-amber-400', icon: Utensils },
    { name: 'Local Transport', amount: transport, color: 'bg-cyan-500', text: 'text-cyan-400', icon: Car },
    { name: 'Activities', amount: activities, color: 'bg-emerald-500', text: 'text-emerald-400', icon: Compass },
    { name: 'Miscellaneous', amount: misc, color: 'bg-slate-500', text: 'text-slate-400', icon: HelpCircle }
  ];

  const calculatedTotal = total || (accommodation + food + transport + activities + misc);

  return (
    <div className="glass-panel rounded-2xl p-6 border border-slate-800/80 shadow-lg select-none">
      <div className="flex items-center gap-2 mb-6 border-b border-slate-800 pb-4">
        <DollarSign className="w-5 h-5 text-indigo-400" />
        <h3 className="text-lg font-bold text-slate-100 font-display">Budget Breakdown</h3>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* Left Side: Stats and bar charts */}
        <div className="space-y-4">
          {categories.map(({ name, amount, color, text, icon: Icon }) => {
            const percentage = calculatedTotal > 0 ? Math.round((amount / calculatedTotal) * 100) : 0;
            return (
              <div key={name} className="space-y-1.5">
                <div className="flex justify-between text-xs font-medium">
                  <span className="flex items-center gap-1.5 text-slate-300">
                    <Icon className={`w-3.5 h-3.5 ${text}`} />
                    {name}
                  </span>
                  <span className="text-slate-200 font-mono font-medium">
                    {formatCurrency(amount, currency)} ({percentage}%)
                  </span>
                </div>
                <div className="h-2 bg-slate-900 rounded-full overflow-hidden border border-slate-800/50">
                  <div
                    className={`h-full ${color} rounded-full transition-all duration-500`}
                    style={{ width: `${percentage}%` }}
                  />
                </div>
              </div>
            );
          })}
        </div>

        {/* Right Side: Total summary card */}
        <div className="flex flex-col justify-center items-center p-6 rounded-2xl bg-indigo-600/5 border border-indigo-500/10 text-center">
          <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">Total Estimated Budget</span>
          <span className="text-3xl font-extrabold text-indigo-300 font-mono mt-2">
            {formatCurrency(calculatedTotal, currency)}
          </span>
          <p className="text-[11px] text-slate-500 mt-4 leading-normal max-w-[240px]">
            * Estimates are approximate suggestions generated by AI based on standard travel categories in the region.
          </p>
        </div>
      </div>
    </div>
  );
}
